"""Phase 3 (Master Handoff 2026-09-23): Part 1 -> Part 2 -> final-segment
orchestration for the 138-second Reel (sections 13-14, AUTO_REEL_MODE).

AUTO_REEL_MODE explicitly forbids "one uncontrolled single huge generation
request": each Part (and the final 18s segment) must be generated by its
own call, "each Part must be stored separately", and the run must
"automatically continue the required Parts" without waiting for the
original prompt's interactive "Continue" - but must still honor its
CONTINUITY RULES (same character, increasing emotional depth, no
repetition, maintain curiosity) by giving each later call a short recap of
what already happened.

This module never calls Gemini directly. `run_part_orchestration()` takes
a `generate_part` callable - (part_plan, source_data, prior_summary) ->
part_dict - so the sequencing, per-part validation, incremental
persistence, resume-without-regenerating, and stop-on-failure behavior
here are fully testable with a fake generator, independent of live API
access (same limitation Phase 1's Blogger fetch and Phase 2's Gemini
request had). The real generator wires this to Gemini using
reel_story.full_prompt_text()/build_reel_source_data(), reusing the
existing GEMINI_API_KEY secret.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Callable

from common import iso_now, read_json, write_json
from reel_story import PART_PLAN, REEL_STYLE, validate_story_json

GeneratePartFn = Callable[[dict[str, Any], dict[str, Any], str], dict[str, Any]]

assert sum(p["target_seconds"] for p in PART_PLAN) == 138, "PART_PLAN must sum to the spec's 138-second target"


class PartGenerationError(RuntimeError):
    """A Part failed to generate, or the assembled story failed validation.
    The whole Reel job stops here - no partial or invented content is used,
    and nothing here ever touches Blogger/Facebook-text state."""


def summarize_part(part: dict[str, Any]) -> str:
    """One line per scene's voiceover - enough continuity context for the
    next Part's CONTINUITY RULES without resending full scene detail
    (keeps later requests small, per "do not make an uncontrolled ...
    request")."""
    lines = [f"Part {part['part_number']} recap:"]
    for scene in part["scenes"]:
        vo = str(scene.get("voiceover", "")).strip()
        if vo:
            lines.append(f"- Scene {scene['scene_number']}: {vo}")
    return "\n".join(lines)


def _prior_summary(completed_parts: list[dict[str, Any]]) -> str:
    ordered = sorted(completed_parts, key=lambda p: p["part_number"])
    return "\n\n".join(summarize_part(p) for p in ordered)


def job_progress_path(job_dir: Path) -> Path:
    return job_dir / "job.json"


def load_progress(job_dir: Path) -> dict[str, Any]:
    return read_json(job_progress_path(job_dir), {})


def _validate_single_part(plan: dict[str, Any], part: dict[str, Any]) -> None:
    if part.get("part_number") != plan["part_number"]:
        raise PartGenerationError(
            f"generator returned part_number {part.get('part_number')!r}, expected {plan['part_number']}"
        )
    scenes = part.get("scenes")
    if not isinstance(scenes, list) or len(scenes) != plan["scene_count"]:
        got = len(scenes) if isinstance(scenes, list) else "non-list"
        raise PartGenerationError(f"Part {plan['part_number']}: expected {plan['scene_count']} scenes, got {got}")
    for scene in scenes:
        for field in ("image_prompt", "motion_prompt", "voiceover"):
            if not str(scene.get(field, "")).strip():
                raise PartGenerationError(f"Part {plan['part_number']} scene {scene.get('scene_number')}: empty {field}")


def detect_duplicate_voiceover(doc: dict[str, Any]) -> list[str]:
    """Structural (not semantic) guard against the CONTINUITY RULES'
    "no repetitive storytelling": flags any voiceover line that appears
    verbatim in more than one scene across the whole Reel."""
    seen: dict[str, int] = {}
    for part in doc.get("parts", []):
        for scene in part.get("scenes", []):
            vo = str(scene.get("voiceover", "")).strip()
            if vo:
                seen[vo] = seen.get(vo, 0) + 1
    return [line for line, count in seen.items() if count > 1]


def run_part_orchestration(
    *,
    job_id: str,
    source_data: dict[str, Any],
    selection: dict[str, Any],
    generate_part: GeneratePartFn,
    job_dir: Path,
) -> dict[str, Any]:
    """Runs Part 1 -> Part 2 -> final segment in order.

    Resumable: if job.json already has some completed parts (e.g. a prior
    run crashed after Part 1), those are reused unchanged and `generate_part`
    is never called again for a part that already succeeded - no wasted or
    duplicate generation, matching the checkpoint discipline already used
    elsewhere in this repo (publisher_inflight.json).
    """
    progress = load_progress(job_dir)
    if progress.get("job_id") != job_id:
        progress = {
            "job_id": job_id,
            "source_article_id": selection.get("reel_source_article_id", ""),
            "source_article_url": selection.get("reel_source_article_url", ""),
            "source_article_title": selection.get("reel_source_article_title", ""),
            "duration_minutes": source_data["duration_minutes"],
            "duration_seconds": source_data["duration_seconds"],
            "style": REEL_STYLE,
            "created_at": iso_now(),
            "parts": [],
            "status": "IN_PROGRESS",
        }

    completed_numbers = {p["part_number"] for p in progress["parts"]}

    for plan in PART_PLAN:
        if plan["part_number"] in completed_numbers:
            continue

        prior_summary = _prior_summary(progress["parts"])
        try:
            part = generate_part(plan, source_data, prior_summary)
            _validate_single_part(plan, part)
        except Exception as exc:
            progress["status"] = "FAILED"
            progress["error"] = str(exc)[:2000]
            write_json(job_progress_path(job_dir), progress)
            if isinstance(exc, PartGenerationError):
                raise
            raise PartGenerationError(f"Part {plan['part_number']} generation failed: {exc}") from exc

        progress["parts"].append(part)
        # Persisted immediately - Part N+1 is never even requested until
        # Part N is durably saved to disk.
        write_json(job_progress_path(job_dir), progress)

    full_doc = {
        "job_id": progress["job_id"],
        "source_article_id": progress["source_article_id"],
        "source_article_url": progress["source_article_url"],
        "source_article_title": progress["source_article_title"],
        "duration_minutes": progress["duration_minutes"],
        "duration_seconds": progress["duration_seconds"],
        "style": progress["style"],
        "parts": sorted(progress["parts"], key=lambda p: p["part_number"]),
    }
    errors = validate_story_json(full_doc)
    duplicates = [] if errors else detect_duplicate_voiceover(full_doc)
    if errors or duplicates:
        progress["status"] = "FAILED"
        progress["error"] = f"schema_errors={errors} duplicate_voiceover={duplicates}"[:2000]
        write_json(job_progress_path(job_dir), progress)
        if errors:
            raise PartGenerationError(f"Assembled story failed schema validation: {errors}")
        raise PartGenerationError(f"Assembled story has repeated voiceover lines across scenes: {duplicates}")

    progress["status"] = "COMPLETE"
    progress["completed_at"] = iso_now()
    write_json(job_progress_path(job_dir), progress)
    return full_doc
